dist: xenial

language: python
python:
    - "3.6"

env:
    - SCVERSION="stable"

before_install:
    - sudo apt-get install -y xz-utils libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0

script:
    - python3 -V
    - sudo rm $(command -v shellcheck)
    - wget https://storage.googleapis.com/shellcheck/shellcheck-${SCVERSION}.linux.x86_64.tar.xz
    - tar --xz -xvf shellcheck-${SCVERSION}.linux.x86_64.tar.xz
    - sudo cp shellcheck-${SCVERSION}/shellcheck /usr/bin/
    - shellcheck --version
    - make check
    - pip install -U -r test-requirements.txt
    - pip install PyGObject semver
    - make flake8
    - make unittest

notifications:
  email: false
